In [2]:
#arrays
cars=['BMW','Ford']
cars

['BMW', 'Ford']

In [4]:
#add array element
cars.append('tata')
cars

['BMW', 'Ford', 'tata', 'tata']

In [5]:
#delete array element
cars.pop(2)
cars

['BMW', 'Ford', 'tata']

In [6]:
cars.remove('Ford')
cars

['BMW', 'tata']

In [7]:
cars.insert(0,"Renault")
cars

['Renault', 'BMW', 'tata']

In [8]:
len(cars)

3

In [9]:
cars.sort()
cars

['BMW', 'Renault', 'tata']

In [10]:
#slice
cars[0:1]

['BMW']

In [11]:
for x in cars:
    print(x)

BMW
Renault
tata


In [17]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [12]:
#numpy 

import numpy as np

arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [19]:
print(type(arr))

<class 'numpy.ndarray'>


In [23]:
#0D
arr = np.array(45)
arr

array(45)

In [31]:
#1d
arr = np.array([1,2,3])

In [22]:
arr

array([1, 2, 3])

In [32]:
#2D
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
arr= list(range(1,11))
for x in arr:
    if x%2==0:
        print(x)

2
4
6
8
10


In [34]:
for x in arr:
    if x%2==0:
        print(x)

2
4
6
8
10


In [35]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
for row in arr:
    for num in row:
        if num % 2 == 0:
            print("Even number:", num)

Even number: 2
Even number: 4
Even number: 6
Even number: 8
Even number: 10
Even number: 12
