In [7]:
#to fetch a 1D array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[2])

3


In [12]:
#to fetch 2D array
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,0]])
#[1,..,5]- index 0 & [5,..,0]- index 1
#print(arr[index,position])
print(arr[1,0])
print(arr[1,2])
print(arr[0,1])

6
8
2


In [13]:
#to fetch 3D array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[3,5,2]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 5 2]]]


In [26]:
#to print a 3D array which is being fetched
#[index,index,position]
print(arr[1,1,2])#3rd element >2nd array of 2nd array
print(arr[1,1,1])#2nd element >2nd array of 2nd array
print(arr[0,1,2])#3rd element >2nd array of 1st array
print(arr[1,0,2])#3rd element >1st array of 2nd array
print(arr[0,0,0])#1st element >1st array of 1st array

2
5
6
9
1


In [38]:
#slice in 1D
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[0:3])
print(arr[0:4])
print(arr[0:4:2])#slice in 1D with iteration of 2
print(arr[3:5:2])
print(arr[::3])

[1 2 3]
[1 2 3 4]
[1 3]
[4]
[1 4]


In [58]:
#slice in 2D
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1,1:2])
print(arr[1,1:3])
print(arr[1,:3])
print(arr[0,:2])

print(arr[0,1:4],arr[1,1:4])

[5]
[5 6]
[4 5 6]
[1 2]
[2 3] [5 6]


In [57]:
print(arr[0:2,0:3]) #print(arr[index(0:2),position needed(0:3)]

[[1 2 3]
 [4 5 6]]


In [56]:
print(arr[0:2,1:4])

[[2 3]
 [5 6]]


In [63]:
#copy 
import numpy as np
arr=np.array([1,2,3,4,5])

x=arr.copy()

print(arr)
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [64]:
#adding another element
import numpy as np
arr=np.array([1,2,3,4,5])

x=arr.copy()
arr[0]=24

print(arr)
print(x)

[24  2  3  4  5]
[1 2 3 4 5]


In [66]:
#view
import numpy as np
arr=np.array([1,2,3,4,5])

x=arr.view()
arr[3]=27
print(arr)
print(x)

[ 1  2  3 27  5]
[ 1  2  3 27  5]


In [75]:
#how to join 2 arrays
#concat in 1D array
import numpy as np
arr1=np.array([2,3,4])
arr2=np.array([6,7,8])

arr=np.concat([arr1,arr2])
print(arr)

[2 3 4 6 7 8]


In [74]:
#how to join 2 arrays
#concat in 2D array
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

arr=np.concat([arr1,arr2])
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
